run_tracado_retas:
	gcc -c tracado_retas.c -lGL -lGLU -lglut && \
	gcc -o tracado_retas tracado_retas.c -lGL -lGLU -lglut -lm && \
	./tracado_retas

run_retas:
	gcc -c retas.c -lGL -lGLU -lglut && \
	gcc -o retas retas.c -lGL -lGLU -lglut -lm && \
	./retas