run_perspectiva:
	gcc -c PerspectivaCG.c -lGL -lGLU -lglut && \
	gcc -o PerspectivaCG PerspectivaCG.c -lGL -lGLU -lglut && \
	./PerspectivaCG

run_ortogonal:
	gcc -c OrtogonalCG.c -lGL -lGLU -lglut && \
	gcc -o OrtogonalCG OrtogonalCG.c -lGL -lGLU -lglut && \
	./OrtogonalCG
