run_circunferencia:
	gcc -c circunferencia.c -lGL -lGLU -lglut && \
	gcc -o circunferencia circunferencia.c -lGL -lGLU -lglut -lm && \
	./circunferencia

run_proj_ortogonal:
	gcc -c proj_ortogonal.c -lGL -lGLU -lglut && \
	gcc -o proj_ortogonal proj_ortogonal.c -lGL -lGLU -lglut -lm && \
	./proj_ortogonal